---
apiVersion: v1
kind: Service
metadata:
  name: vault-root
  namespace: {{ .Values.namespace }}
  labels:
    app: vault-root
spec:
  clusterIP: None
  ports:
  - name: root
    port: {{ pluck .Values.werf.env .Values.port | first | default .Values.port._default }}
    protocol: TCP
    targetPort: {{ pluck .Values.werf.env .Values.port | first | default .Values.port._default }}
  selector:
    app: vault-root
