version: "3"

services:
  rolebinding-watcher:
    image: ubuntu:20.04
    platform: linux/amd64
    container_name: rolebinding-watcher
    volumes:
      - "../docker/kafka/ca.crt:/tmp/ca.crt:ro"
      - "../docker/kafka/client.crt:/tmp/client.crt:ro"
      - "../docker/kafka/client.key:/tmp/client.key:ro"
      - "./build/rolebinding-watcher:/bin/rolebinding-watcher:ro"
    environment:
      - KAFKA_ENDPOINTS=kafka:9093
      - KAFKA_USE_SSL=true
      - KAFKA_CA_PATH=/tmp/ca.crt
      - KAFKA_PRIVATE_CERT_PATH=/tmp/client.crt
      - KAFKA_PRIVATE_KEY_PATH=/tmp/client.key
      - CLIENT_TOPIC=${CLIENT_TOPIC}
      - CLIENT_GROUP_ID=${CLIENT_GROUP_ID}
      - CLIENT_ENCRYPTION_PUBLIC_KEY=${CLIENT_ENCRYPTION_PUBLIC_KEY}
      - CLIENT_ENCRYPTION_PRIVATE_KEY=${CLIENT_ENCRYPTION_PRIVATE_KEY}
      - HTTP_URL=${HTTP_URL}
    command: /bin/rolebinding-watcher

networks:
  default:
    name: negentropy
    external: true
